### ISSUE TITLE
Don't create entrypoint if it exists as js

### ISSUE THREAD

**Issue by jasonkarns** [linemanjs/lineman-browserify#11]

**Comment by jasonkarns** [comment]
b5a11ae44cd0db7ddf30174a0f5e4eed8837734e

**Comment by searls** [comment]
Not just that it should be looking at files.browserify.entrypoint. If the user changes it later and then installs a new version it's not enough to check coffee or JS.

**Comment by jasonkarns** [comment]
Yeah, this is just a half step. To avoid the general rename case we have two options that I see.

1) don't run this script at install time (perhaps by tying it into the `lineman install` subcommand linemanjs/lineman#218)
2) pulling the config value from lineman itself. which doesn't really make sense during the _first_ install because lineman may not even be available at that point.

Does npm fire off the postinstall scripts as each package is installed? Or queue them up and fire them off after the entire install is finished?

**Comment by searls** [comment]
I think lineman will always be available at install time. As a peer dep, npm will ensure it's there first.
