### ISSUE TITLE
Incompatible with Handlebars

### ISSUE THREAD

**Issue by erichiggins** [linemanjs/lineman-browserify#16]
The lineman-browserify plugin may be incompatible with Handlebars. Trying to convert `hello.us` to `hello.hbs` in a fairly default setup threw the following exception:

```
Uncaught ReferenceError: Handlebars is not defined 
```

There doesn't seem to be any documentation to help with setting this up.

**Comment by searls** [comment]
Is that error occurring in the browser console? If so you may only need to add the handlebars runtime to vendor/js.

**Comment by erichiggins** [comment]
Yes, it's in the console. I already added `handlebars.runtime.js` to `vendor/js`.

**Comment by searls** [comment]
Ah, fair enough then. Could you share an example project so that I might try to debug it?

**Comment by erichiggins** [comment]
A default install should do it, with these minor modifications:

`app/js/entrypoint.coffee`

```
window._ = require("underscore")
window.Handlebars = require("handlebars.runtime")
require("./hello")
```

`app/js/hello.coffee`
_Note the change of `hello.us` to `hello.hbs`._

```
window.helloText = -> 'Hello, World!'

window.hello = ->
  html = JST['app/templates/hello.hbs'](text: helloText())
  document.body.innerHTML += html

if window.addEventListener
  window.addEventListener('DOMContentLoaded', hello, false)
else
  window.attachEvent('onload', hello)
```

`app/templates/hello.hbs`

```
<div class="hello">
  {{ text }}
</div>
```

Then, copy `handlebars.runtime.js` into `vendor/js`, execute `lineman run`, open [http://localhost:8000](http://localhost:8000), and see the raised exception.

**Comment by searls** [comment]
I have a solution for you!

First of all, if you're going to use handlebars templates (thanks to the need for the client-side runtime), the templates need to be concat'd after the browserify bundle. So in your `config/application` file, try this config:

``` javascript
    concat_sourcemap: {
      js: {
        src: [
          "<%= files.browserify.generated %>",
          "<%= files.template.generated %>"
        ]
      }
    }
```

The next issue is how you pull down the runtime.

As it happens, the `handlebars.runtime.js` distribution unhelpfully spits out an empty object when you `require` it with browserify. I don't know why this is, but Ember does the same thing. Instead, to get it to work, I installed it with npm using `npm i --save-dev handlebars@1.3.0` and then I required it like this: `window.Handlebars = require("handlebars/runtime")["default"]`

Once I did these things, I got it working.

**Comment by erichiggins** [comment]
I also had to copy most of the contents from `node_modules/handlebars/dist/cjs/` into `vendor/js`, which is annoying. It'd be really helpful if you could add some official documentation about this. ;)

**Comment by searls** [comment]
Why did you have to copy stuff to vendor/js? I didn't in my example

**Comment by erichiggins** [comment]
Oh, because I was doing something wrong. :)

I tried again, this time just copying `handlebars.runtime.amd.js` (instead of `handlebars.runtime.js`) so that `handlebars/runtime` would be provided for the `require()` statement you listed. That seemed to do the trick.

I was thrown off by your use of `npm` and the `/` in the `require` statement. When I took a look at the contents of `node_modules/handlebars/runtime.js`, I saw that it referenced the `dist/cjs/` stuff. Wrong rabbit hole.

**Comment by searls** [comment]
Right on. This stuff is confusing to us to because we don't use it extensively and it can be used in so many ways

**Comment by erichiggins** [comment]
Fair. Any chance you could add a unit test and/or documentation or something to help other folks out that may fumble over the same stuff that I did?

**Comment by searls** [comment]
I'm still not entirely sure what generally applicable thing we just uncovered that could be documented. I get the sense you understand it better, if anything. A PR to the README would be very much appreciated

**Comment by erichiggins** [comment]
Seems pretty specific to Handlebars rather than generally applicable, unless there are other libraries that have weak support for AMD/CJS/etc.

Anyway, we can discuss it more in a PR for the README, which I'll submit to you later today.

Thanks for the help!

**Comment by erichiggins** [comment]
It looks like I've run into another problem with this -- when I try to call `view.render()` in my source, it leads to a failure on `window.JST` being undefined. Commenting out the single `render()` call allows the page to load without error, but is obviously not that useful.

 Using the snippet you gave for `config/application.js:concat_sourcemap`, the resulting files cause `window.JST` to be defined at the end of `app.js`. Note that this [differs from the original configuration](https://github.com/linemanjs/lineman/blob/master/config/plugins/concat_sourcemap.coffee#L8).

Is there a way to force browserify/lineman to define the same source order (vendor js, templates, application)? Maybe I'm doing something else wrong?

**Comment by erichiggins** [comment]
Nevermind, just having a noob moment and forgot to fire the app initializer with onload. :-\
