### ISSUE TITLE
compile fails because coffeeify transform doesn't exist in root level

### ISSUE THREAD

**Issue by davemo** [linemanjs/lineman-browserify#4]
grunt-browserify seems to be looking for the configured `coffeeify` transform at `{lineman_project}/node_modules/coffeeify` instead of `{lineman_project}/node_modules/lineman-browserify/node_modules/coffeeify` which is the cause of explosions

![screen shot 2014-02-25 at 3 20 53 pm](https://f.cloud.github.com/assets/69559/2262461/5b36e212-9e5a-11e3-81f1-36773be7e945.png)

I'm a little confused because lineman-browserify has coffeeify as a dependency in its package.json file.

I can add documentation to the readme that tells people they need to `npm install coffeeify --save-dev` in their `{lineman_project}` dir, but it would be nice if the plugin was able to pull in all things necessary for compilation to work.

Thoughts @searls @jasonkarns ?

If you want to replicate, here's a little repo I made: https://github.com/davemo/browserify-testing

You can see my changes to the two .coffee files here:

https://github.com/davemo/browserify-testing/blob/master/app/js/app.coffee
https://github.com/davemo/browserify-testing/blob/master/app/js/hello.coffee

**Comment by jasonkarns** [comment]
It ought to be a peerDep. Nothing in lineman-browserify directly does `require('coffeeify')`. The require call only happens in the main lineman project level. So it needs to be installed at that level.

*disclaimer: untested :smile:

**Comment by jasonkarns** [comment]
Come to think of it, there is rarely a case where any of the lineman-\* plugins ought to have any direct dependencies.
